image: archlinux                                                                         
packages:                                                                                       
  - go
  - webkit2gtk
sources:                                                                                        
  - https://git.sr.ht/~dvn/HyperWalker                                                          
tasks:                                                                                          
  - build: |
      export PATH=$PATH:$HOME/go/bin
      go get -v github.com/rakyll/statik
      cd HyperWalker
      go generate
      go get -d ./...
      go build -o hyperwalker main.go
