before_script:
    - wget --quiet https://github.com/earthly/earthly/releases/download/v0.6.14/earthly-linux-amd64 -O earthly
    - chmod +x earthly
    - export FORCE_COLOR=1
    - ./earthly config global.disable_analytics true
    - ./earthly config global.disable_log_sharing true
    - ./earthly bootstrap
    - rm -f ~/.docker/config.json
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY} 

nix build:
  image: nixos/nix
  stage: build
  before_script:
    - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
  script:
    - nix-channel --update
    - nix flake update
    - nix build

earthly build:
  tags: [kvm]
  stage: build
  script:
    - ./earthly --ci --output --push +build
    - ./earthly --ci --output --push +docker
    - ls
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - build/

earthly test:
  tags: [kvm]
  stage: test
  needs: ["earthly build"]
  script:
    - ./earthly --ci --output --push +firefox-image
    - ./earthly --ci --output --push +application-test
  artifacts:
    paths:
      - test-snapshot.html

nix test:
  image: nixos/nix
  stage: test
  needs: ["nix build"]
  before_script:
    - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
  script:
    - nix-channel --update
    - nix flake update
    - mkdir -p $HOME/.hyperwalker/logs
    - nix run . -- -url https://en.wikipedia.org/wiki/Special:Random || true ;
      sleep 5 ;
      nix run . -- -url https://en.wikipedia.org/wiki/Special:Random || true ;
      sleep 5 ;
      nix run . -- -url https://en.wikipedia.org/wiki/Special:Random
    - mv /tmp/*hyperwalker*.html test-snapshot.html
  artifacts:
    paths:
      - test-snapshot.html
